/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/audit/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Handle `GET /audit/events?limit=`: the most recent audit events, newest
         *     first, capped at [`MAX_LIMIT`] regardless of what the caller asks for.
         */
        get: operations["list_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Handle `POST /auth/login`.
         * @description `200` with the admin id and fresh session/CSRF cookies on success; `401`
         *     for invalid credentials (identical for a wrong password and a nonexistent
         *     account); `429` with `Retry-After` when the IP or account has hit the
         *     app-level rate limit, or when the account/IP is locked out (see
         *     [`LoginError::TooManyAttempts`] — a distinct mechanism from the rate limit:
         *     lockout counts *failures*, the rate limit counts *every* attempt); `500` on
         *     an internal failure. Every successful login issues a brand-new session —
         *     there is no "reuse the prior session" path — which is what satisfies
         *     session rotation on login.
         */
        post: operations["login_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Handle `POST /auth/logout`: revoke the session server-side, record the
         *     event to the audit trail, and clear both cookies. Requires (via
         *     [`require_session`]) a valid session and a matching CSRF header — logout
         *     is a mutation like any other.
         */
        post: operations["logout_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Handle `GET /auth/me`: report the authenticated admin's id and role, so
         *     frontend guards can hide routes/actions the role does not permit without
         *     a separate round trip. Any authenticated role may call this — it is not
         *     itself role-gated (see [`crate::rbac::require_role`] for endpoints that
         *     are).
         */
        get: operations["me_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe: `200 OK` when ready, `503 Service Unavailable` otherwise.
         * @description Awaits the application service, which in turn probes the live database, so a
         *     down or unreachable Postgres surfaces here as `503`.
         */
        get: operations["health_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description One audit event, as returned to the admin panel. */
        EventOut: {
            /** @description The resolved admin id, when the event maps to a known account. */
            admin_id?: string | null;
            /**
             * @description The email submitted, for login events (kept even when it matched no
             *     account).
             */
            email_attempted?: string | null;
            /**
             * @description The event type (`login_succeeded`, `login_failed`, `locked_out`,
             *     `logged_out`).
             */
            event_type: string;
            /** @description The event's opaque id. */
            id: string;
            /** @description The client IP the request came from. */
            ip: string;
            /**
             * Format: int64
             * @description When the event happened, as Unix epoch seconds.
             */
            occurred_at_epoch: number;
            /** @description The client `User-Agent`, if any. */
            user_agent?: string | null;
        };
        /** @description The JSON body of a login request. */
        LoginBody: {
            /**
             * @description The administrator's email address.
             * @example admin@example.com
             */
            email: string;
            /** @description The administrator's password. */
            password: string;
        };
        /** @description The success body: the authenticated administrator's id. */
        LoginOk: {
            /** @description The authenticated administrator's opaque id. */
            admin_id: string;
        };
        /**
         * @description The body `GET /auth/me` returns: enough for the frontend to know who is
         *     logged in and which role's guards to apply.
         */
        MeOut: {
            /** @description The authenticated administrator's opaque id. */
            admin_id: string;
            /** @description The administrator's role (e.g. `admin`). */
            role: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_events: {
        parameters: {
            query?: {
                /** @description Maximum number of events to return (default 50, capped at 200). */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent audit events, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"][];
                };
            };
            /** @description No valid session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authenticated but not the admin role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginBody"];
            };
        };
        responses: {
            /** @description Signed in; sets session and csrf cookies */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginOk"];
                };
            };
            /** @description Invalid credentials (wrong password or unknown account) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rate-limited or locked out; carries Retry-After */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out; clears the session and csrf cookies */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No valid session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or mismatched CSRF header */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The authenticated admin's id and role */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description No valid session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not ready (database unreachable) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
