/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/audit/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Handle `GET /audit/events?limit=`: the most recent audit events, newest
         *     first, capped at [`MAX_LIMIT`] regardless of what the caller asks for.
         */
        get: operations["list_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Handle `POST /auth/login`.
         * @description `200` with the admin id and fresh session/CSRF cookies on success; `401`
         *     for invalid credentials (identical for a wrong password and a nonexistent
         *     account); `429` with `Retry-After` when the IP or account has hit the
         *     app-level rate limit, or when the account/IP is locked out (see
         *     [`LoginError::TooManyAttempts`] — a distinct mechanism from the rate limit:
         *     lockout counts *failures*, the rate limit counts *every* attempt); `500` on
         *     an internal failure. Every successful login issues a brand-new session —
         *     there is no "reuse the prior session" path — which is what satisfies
         *     session rotation on login.
         */
        post: operations["login_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Handle `POST /auth/logout`: revoke the session server-side, record the
         *     event to the audit trail, and clear both cookies. Requires (via
         *     [`require_session`]) a valid session and a matching CSRF header — logout
         *     is a mutation like any other.
         */
        post: operations["logout_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Handle `GET /auth/me`: report the authenticated admin's identity and
         *     profile fields, so the frontend can display them without a separate round
         *     trip. Any authenticated role may call this — it is not itself role-gated
         *     (see [`crate::rbac::require_role`] for endpoints that are).
         */
        get: operations["me_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/oauth/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /auth/oauth/providers`: list the enabled provider ids. Public — the
         *     login page calls it before any session exists.
         */
        get: operations["providers_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe: `200 OK` whenever the process is running. No dependency is
         *     checked, so a slow or briefly-unreachable database never turns into a restart.
         */
        get: operations["liveness_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe: `200 OK` when ready, `503 Service Unavailable` otherwise.
         * @description Awaits the application service, which in turn probes the live database, so a
         *     down or unreachable Postgres surfaces here as `503`.
         */
        get: operations["readiness_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Handle `GET /transactions`: a filtered, paginated payment list, newest
         *     first.
         */
        get: operations["list_transactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Handle `GET /transactions/{id}`: one payment with its full status history. */
        get: operations["get_transaction"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/{id}/refund": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Handle `POST /transactions/{id}/refund`: refund a captured payment in full.
         *     Admin-only (via [`require_role`]) and CSRF-checked (via [`require_session`]).
         */
        post: operations["refund_transaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description The JSON body every error response carries. */
        ErrorResponse: {
            /**
             * @description A stable, machine-readable error code (e.g. `unauthorized`,
             *     `not_found`, `validation_failed`).
             */
            code: string;
            /** @description Per-field validation messages, present only on a `422` response. */
            fields?: {
                [key: string]: string;
            } | null;
            /** @description A human-readable, client-safe message. Never contains internal detail. */
            message: string;
            /**
             * @description A correlation id, also logged server-side, so a client-reported error
             *     can be matched to its log line.
             */
            trace_id: string;
        };
        /** @description One audit event, as returned to the admin panel. */
        EventOut: {
            /** @description The resolved admin id, when the event maps to a known account. */
            admin_id?: string | null;
            /**
             * @description The email submitted, for login events (kept even when it matched no
             *     account).
             */
            email_attempted?: string | null;
            /**
             * @description The event type (`login_succeeded`, `login_failed`, `locked_out`,
             *     `logged_out`).
             */
            event_type: string;
            /** @description The event's opaque id. */
            id: string;
            /** @description The client IP the request came from. */
            ip: string;
            /**
             * Format: int64
             * @description When the event happened, as Unix epoch seconds.
             */
            occurred_at_epoch: number;
            /** @description The client `User-Agent`, if any. */
            user_agent?: string | null;
        };
        /** @description The JSON body of a login request. */
        LoginBody: {
            /**
             * @description The administrator's email address.
             * @example admin@example.com
             */
            email: string;
            /** @description The administrator's password. */
            password: string;
        };
        /** @description The success body: the authenticated administrator's id. */
        LoginOk: {
            /** @description The authenticated administrator's opaque id. */
            admin_id: string;
        };
        /**
         * @description The body `GET /auth/me` returns: enough for the frontend to know who is
         *     logged in and which role's guards to apply, plus profile fields for the UI.
         */
        MeOut: {
            /** @description The authenticated administrator's opaque id. */
            admin_id: string;
            /** @description An optional display name for the profile UI. */
            display_name?: string | null;
            /** @description The administrator's email address. */
            email: string;
            /** @description The administrator's role (e.g. `admin`). */
            role: string;
        };
        /** @description The configured OAuth providers, for the login UI to render a button per one. */
        ProvidersOut: {
            /**
             * @description The enabled provider ids (e.g. `["google"]`), sorted. Empty when OAuth
             *     is configured but has no providers; the whole route is absent (`404`)
             *     when OAuth is disabled entirely — the UI treats both as "no providers".
             */
            providers: string[];
        };
        /** @description The result of a successful refund. */
        RefundOut: {
            /** @description The status the payment moved to (`refunded` or `partially_refunded`). */
            status: string;
        };
        /** @description One recorded status change in a payment's history. */
        StatusChangeOut: {
            /** @description The prior status, or `null` for the row recording creation. */
            from?: string | null;
            /**
             * Format: int64
             * @description When the transition happened, as Unix epoch seconds.
             */
            occurred_at_epoch: number;
            /** @description An optional human-readable reason (a decline code, `admin_refund`, ...). */
            reason?: string | null;
            /** @description The status moved to. */
            to: string;
        };
        /** @description A payment with its full status history — the detail view's payload. */
        TransactionDetailOut: {
            /** @description Every recorded status change, oldest first. */
            history: components["schemas"]["StatusChangeOut"][];
            /** @description The payment itself. */
            transaction: components["schemas"]["TransactionOut"];
        };
        /** @description One payment row, as returned to the admin panel. */
        TransactionOut: {
            /**
             * Format: int64
             * @description The amount, in the currency's minor units (e.g. cents) — never a float.
             */
            amount_minor_units: number;
            /**
             * Format: int64
             * @description When the payment was created, as Unix epoch seconds.
             */
            created_at_epoch: number;
            /** @description ISO 4217 currency code (`USD`, ...). */
            currency: string;
            /** @description The payment's opaque id (its primary key). */
            id: string;
            /** @description The provider's reference, once one exists. */
            provider_reference?: string | null;
            /** @description The current status (`created`, `captured`, `refunded`, ...). */
            status: string;
            /**
             * Format: int64
             * @description When the payment's status last changed, as Unix epoch seconds.
             */
            updated_at_epoch: number;
        };
        /** @description One page of transactions plus the total matching the filter. */
        TransactionPage: {
            /** @description The payments on this page, newest first. */
            items: components["schemas"]["TransactionOut"][];
            /**
             * Format: int32
             * @description The page size that was applied (after capping).
             */
            limit: number;
            /**
             * Format: int32
             * @description The offset that was applied.
             */
            offset: number;
            /**
             * Format: int64
             * @description Total payments matching the filter across all pages.
             */
            total: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_events: {
        parameters: {
            query?: {
                /** @description Maximum number of events to return (default 50, capped at 200). */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent audit events, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"][];
                };
            };
            /** @description No valid session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authenticated but not the admin role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    login_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginBody"];
            };
        };
        responses: {
            /** @description Signed in; sets session and csrf cookies */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginOk"];
                };
            };
            /** @description Invalid credentials (wrong password or unknown account) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Malformed request (per-field validation) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Rate-limited or locked out; carries Retry-After */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    logout_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out; clears the session and csrf cookies */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No valid session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or mismatched CSRF header */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The authenticated admin's identity and profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description No valid session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    providers_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The enabled OAuth provider ids */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvidersOut"];
                };
            };
        };
    };
    liveness_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The process is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readiness_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready to serve */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not ready (database unreachable) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_transactions: {
        parameters: {
            query?: {
                /** @description Only payments in this status (e.g. `captured`, `refunded`). */
                status?: string;
                /** @description Only payments created at or after this Unix epoch second (inclusive). */
                created_after?: number;
                /** @description Only payments created strictly before this Unix epoch second. */
                created_before?: number;
                /** @description Page size (default 50, capped at 200). */
                limit?: number;
                /** @description Rows to skip, for paging (default 0). */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of transactions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionPage"];
                };
            };
            /** @description No valid session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid status filter (per-field) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_transaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The payment id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The payment and its status history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionDetailOut"];
                };
            };
            /** @description No valid session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No such payment */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    refund_transaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The payment id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Refunded; the payment's new status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefundOut"];
                };
            };
            /** @description No valid session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not the admin role, or missing/mismatched CSRF */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No such payment */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Payment is not in a refundable state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The provider declined the refund */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The provider was unavailable */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
